#define MAXTOUCH_BOOTLOADER_GESTURE
#define MOUSE_EXTENDED_REPORT
#define MXT_ENABLE_STYLUS 0
#define DIGITIZER_HAS_STYLUS true
#define DIGITIZER_CONTACT_COUNT 16

// for printing floats
#undef PRINTF_SUPPORT_DECIMAL_SPECIFIERS
#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 1
