#define MAXTOUCH_BOOTLOADER_GESTURE
#define MOUSE_EXTENDED_REPORT
#define DIGITIZER_HAS_STYLUS true

// for printing floats
#undef PRINTF_SUPPORT_DECIMAL_SPECIFIERS
#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 1
