#pragma once

// 2000 max dpi before smoothing is applied
#define PLOOPY_DPI_OPTIONS { 2000 }
#define PLOOPY_DPI_DEFAULT 0

#define PLOOPY_DRAGSCROLL_DIVISOR 1.0
#define PLOOPY_DRAGSCROLL_DIVISOR_H PLOOPY_DRAGSCROLL_DIVISOR
#define PLOOPY_DRAGSCROLL_DIVISOR_V PLOOPY_DRAGSCROLL_DIVISOR
#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT

#define MOUSE_EXTENDED_REPORT

#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 120
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 0
